### PR TITLE
add support for PhoneNumbers parameter - an array of phone numbers

### PR DESCRIPTION
**Pull request by frantisekbrabec**

### CODE REVIEW

**Comment by frantisekbrabec** [comment]
yes, whether to add PhoneNumbers or replace the existing PhoneNumber with is was something I was also wondering about. I think PhoneNumber is really an invalid parameter/a typo so removing it would be a fix but as you said, doing so breaks existing calls. I suppose we should preserve... I have made no changes that affect handling on AssignedDID and StatusPostBackURL so it should behave the same as it did before.

**Comment by revmischa** [comment]
Well it'd be passing in blank values instead of the params not existing at all. One hopes this would not affect the behavior but sometimes the presence of blank values is not treated the same as the lack of presence.
My main concern is just not breaking existing users of the current module. If they upgrade to this newer version, their code will stop working without so much as a warning. This makes people sad and come find this commit on github and then dox you and ruin your life.

**Comment by frantisekbrabec** [comment]
ok, added compatibility with the old parameter (if it exists, use that, otherwise use PhoneNumbers). How about that?

**Comment by revmischa** [comment]
On CPAN: https://metacpan.org/release/Net-SMS-CDYNE

**Pull request merged**
